"""empty message

Revision ID: 9fedbf3980fa
Revises: b60eb471bbdb
Create Date: 2023-10-31 11:56:59.109117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fedbf3980fa'
down_revision = 'b60eb471bbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
