"""empty message

Revision ID: b60eb471bbdb
Revises: db6e4b6cdfa9
Create Date: 2023-10-22 18:25:51.467319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60eb471bbdb'
down_revision = 'db6e4b6cdfa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('trim',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('trim',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('make',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
