"""empty message

Revision ID: c826aea0da16
Revises: f09f1eb8b6c8
Create Date: 2023-10-31 14:16:17.170872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c826aea0da16'
down_revision = 'f09f1eb8b6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
